spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8080

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY:}
